# Generated by Django 3.2 on 2021-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fId', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=8)),
                ('subjectCode', models.CharField(max_length=20)),
                ('assignment1', models.FloatField(default=0.0)),
                ('assignment2', models.FloatField(default=0.0)),
                ('classtest1', models.FloatField(default=0.0)),
                ('classtest2', models.FloatField(default=0.0)),
                ('midTerm', models.FloatField(default=0.0)),
                ('endTerm', models.FloatField(default=0.0)),
            ],
        ),
    ]
