# Generated by Django 2.0.2 on 2021-05-03 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0002_faculty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
