# Generated by Django 2.0.2 on 2021-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0003_auto_20210503_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Credit',
            field=models.FloatField(default=0.0),
        ),
    ]
