# Generated by Django 2.0.2 on 2021-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0004_faculty_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.FloatField(default=0.0)),
                ('Sem', models.FloatField(default=0.0)),
                ('sgpa', models.FloatField(default=0.0)),
            ],
        ),
    ]
