# Generated by Django 2.0.2 on 2021-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0005_sem_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem_grade',
            name='rollNo',
            field=models.CharField(max_length=8),
        ),
    ]
