# Generated by Django 2.0.2 on 2021-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0006_auto_20210503_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem_grade',
            name='totcredit',
            field=models.IntegerField(default=0),
        ),
    ]
